blank_issues_enabled: false
contact_links:
  - name: Question / Support
    url: https://github.com/Kernel-Heim/forge-cute-py/discussions
    about: Ask questions, get help, or discuss general topics in GitHub Discussions
